## Generated by GPT-5.0

import numpy as np
import open3d as o3d
from typing import List, Tuple

def get_obb(pts, remove_outlier=False):
    if not isinstance(pts, np.ndarray):
        pts = pts.detach().cpu().numpy()
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(pts)
    # remove_statistical_outlier
    if remove_outlier:
        cl, ind = pcd.remove_statistical_outlier(nb_neighbors=20, std_ratio=2.0)
        pcd = pcd.select_by_index(ind)
    obb = pcd.get_oriented_bounding_box()
    return obb

# ------------------- Geometry helpers -------------------

def _closest_point_on_obb(point: np.ndarray, obb: o3d.geometry.OrientedBoundingBox) -> np.ndarray:
    """
    Closest point on OBB (surface or interior) to a given 3D point.
    """
    C = np.asarray(obb.center)
    R = np.asarray(obb.R)        # columns are local axes
    half = np.asarray(obb.extent) * 0.5

    # to OBB local coords
    p_local = R.T @ (point - C)
    # clamp to box
    p_clamped = np.clip(p_local, -half, half)
    # back to world
    return R @ p_clamped + C

def _segment_segment_closest_points(p1, q1, p2, q2, eps=1e-12):
    """
    Closest points between two line segments p1-q1 and p2-q2 in 3D.
    Returns (c1, c2, dist).
    Based on the classic algorithm by Dan Sunday (geomalgorithms.com).
    """
    p1 = np.asarray(p1, float); q1 = np.asarray(q1, float)
    p2 = np.asarray(p2, float); q2 = np.asarray(q2, float)

    d1 = q1 - p1  # direction vector of segment S1
    d2 = q2 - p2  # direction vector of segment S2
    r  = p1 - p2
    a = d1.dot(d1)
    e = d2.dot(d2)
    b = d1.dot(d2)
    c = d1.dot(r)
    f = d2.dot(r)

    # parameters on [0,1]
    s, t = 0.0, 0.0

    if a <= eps and e <= eps:
        # both segments degenerate to points
        c1 = p1
        c2 = p2
        return c1, c2, np.linalg.norm(c1 - c2)

    if a <= eps:
        # first segment degenerate
        s = 0.0
        t = np.clip(f / e, 0.0, 1.0) if e > eps else 0.0
    elif e <= eps:
        # second segment degenerate
        t = 0.0
        s = np.clip(-c / a, 0.0, 1.0)
    else:
        denom = a*e - b*b
        if denom != 0.0:
            s = np.clip((b*f - c*e) / denom, 0.0, 1.0)
        else:
            s = 0.0  # parallel; pick arbitrary s
        t = (b*s + f) / e
        if t < 0.0:
            t = 0.0
            s = np.clip(-c / a, 0.0, 1.0)
        elif t > 1.0:
            t = 1.0
            s = np.clip((b - c) / a, 0.0, 1.0)

    c1 = p1 + s * d1
    c2 = p2 + t * d2
    return c1, c2, np.linalg.norm(c1 - c2)

def _obb_corners_and_edges(obb: o3d.geometry.OrientedBoundingBox):
    """
    Returns (corners[8,3], edges[12,(2,3)]) with stable indexing.
    We synthesize corners from center/axes/extents to control ordering.
    """
    C = np.asarray(obb.center)
    R = np.asarray(obb.R)
    half = np.asarray(obb.extent) * 0.5

    ex, ey, ez = R[:, 0], R[:, 1], R[:, 2]
    u = ex * half[0]
    v = ey * half[1]
    w = ez * half[2]

    # stable order:
    # 0..3: bottom (-w), counter-clockwise; 4..7: top (+w)
    corners = np.stack([
        C - u - v - w,  # 0
        C + u - v - w,  # 1
        C + u + v - w,  # 2
        C - u + v - w,  # 3
        C - u - v + w,  # 4
        C + u - v + w,  # 5
        C + u + v + w,  # 6
        C - u + v + w   # 7
    ], axis=0)

    edges_idx = [
        (0,1), (1,2), (2,3), (3,0),  # bottom
        (4,5), (5,6), (6,7), (7,4),  # top
        (0,4), (1,5), (2,6), (3,7)   # verticals
    ]
    edges = [(corners[i], corners[j]) for (i, j) in edges_idx]
    return corners, edges

# ------------------- Main function -------------------

def obb_min_distance(obb_a: o3d.geometry.OrientedBoundingBox,
                     obb_b: o3d.geometry.OrientedBoundingBox,
                     early_exit_tol: float = 0.0):
    """
    Compute the minimum distance between two OBBs (Open3D) and closest points.

    Args:
        obb_a, obb_b: open3d.geometry.OrientedBoundingBox
        early_exit_tol: if distance <= this, return early (e.g., 0.0)

    Returns:
        dist (float), pa (np.ndarray, shape (3,)), pb (np.ndarray, shape (3,))
        where pa and pb are the closest points on obb_a and obb_b respectively.
    """
    # Gather primitive sets
    corners_a, edges_a = _obb_corners_and_edges(obb_a)
    corners_b, edges_b = _obb_corners_and_edges(obb_b)

    best_d = np.inf
    best_pa = None
    best_pb = None

    # 1) Vertex -> OBB (A's corners to B)
    for p in corners_a:
        q = _closest_point_on_obb(p, obb_b)
        d = np.linalg.norm(p - q)
        if d < best_d:
            best_d, best_pa, best_pb = d, p, q
            if best_d <= early_exit_tol:
                return best_d, best_pa, best_pb

    # 2) Vertex -> OBB (B's corners to A)
    for p in corners_b:
        q = _closest_point_on_obb(p, obb_a)
        d = np.linalg.norm(p - q)
        if d < best_d:
            best_d, best_pa, best_pb = d, q, p  # note: pa on A, pb on B
            if best_d <= early_exit_tol:
                return best_d, best_pa, best_pb

    # 3) Edge ↔ Edge pairs
    for (a0, a1) in edges_a:
        for (b0, b1) in edges_b:
            ca, cb, d = _segment_segment_closest_points(a0, a1, b0, b1)
            if d < best_d:
                best_d, best_pa, best_pb = d, ca, cb
                if best_d <= early_exit_tol:
                    return best_d, best_pa, best_pb

    return float(best_d), np.asarray(best_pa), np.asarray(best_pb)



# ------------------- Example usage -------------------
if __name__ == "__main__":
    # Make two example OBBs (or use pcd.get_oriented_bounding_box())
    obb1 = o3d.geometry.OrientedBoundingBox(center=[0,0,0],
                                            R=np.eye(3),
                                            extent=[1, 0.5, 0.5])
    R2 = o3d.geometry.get_rotation_matrix_from_xyz([0.3, 0.4, 0.1])
    obb2 = o3d.geometry.OrientedBoundingBox(center=[1.0, 0.2, 0.1],
                                            R=R2,
                                            extent=[0.6, 0.4, 0.7])



    dist, pa, pb = obb_min_distance(obb1, obb2, early_exit_tol=0.0)
    print("Distance:", dist)
    print("Point on A:", pa)
    print("Point on B:", pb)

    # Visualize
    obb1.color = [1, 0, 0]
    obb2.color = [0, 1, 0]
    line_set = o3d.geometry.LineSet(
        points=o3d.utility.Vector3dVector([pa, pb]),
        lines=o3d.utility.Vector2iVector([[0,1]])
    )

    line_set.colors = o3d.utility.Vector3dVector([[0,0,1]])
    axis = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.5, origin=[0,0,0])
    o3d.visualization.draw_geometries([obb1, obb2, line_set, axis])


    # Example: make a few OBBs
    obb1 = o3d.geometry.OrientedBoundingBox(center=[0,0,0], R=np.eye(3), extent=[1, 0.5, 0.5])
    obb2 = o3d.geometry.OrientedBoundingBox(center=[1,0.2,0.1],
                                            R=o3d.geometry.get_rotation_matrix_from_xyz([0.3,0.4,0.1]),
                                            extent=[0.6,0.4,0.7])
    obb3 = o3d.geometry.OrientedBoundingBox(center=[-0.5,1.0,0.0], R=np.eye(3), extent=[0.8,0.6,0.5])

    # Pairwise mode
    dists, pa, pb = obb_min_distance_batch([obb1, obb2], [obb2, obb3], pairwise=True)
    print("Pairwise distances:", dists)

    # Full matrix
    dmat, pa_mat, pb_mat = obb_min_distance_batch([obb1, obb2, obb3])
    print("Distance matrix:\n", dmat)